---
language: python
python:
  "3.6"

# Install python packages for ansible and linters.
install:
  - "pip install -r requirements.txt"

# Execute linting (and future unit tests) before running the main STIG tool.
# If any of these tasks fail, the entire build fails immediately.
before_script:
  - "echo $PATH"
  - "make lint"

# Run the script four times, using three explicit verbosities and one
# default setting just to make sure it doesn't barf exceptions.
script:
  - "make run"
...
